myStr='Lindo idiota'

# print(dir(myStr))
# print(myStr.upper())
# print(myStr.lower())
# print(myStr.swapcase())
# print(myStr.capitalize())
# newStr= myStr.replace('Lindo',"horrible,")
# print(newStr.upper())
# count= myStr.count(' ')
# print(count)
# Inicia=myStr.startswith('Lo')
# print(Inicia)
# Termina=myStr.endswith('Idiota')
# print(Termina)
# divide=myStr.split('i')
# print(divide)
# longitud= len(myStr)
# print(longitud)